export const assetPaths = {
  iconsSprite: "/icons.svg",
  marketing: {
    defaultOgImage: "/marketing/remix-run-share-thumbnail.png",
  },
  jam2025: {
    backgroundMask: "/jam/2025/images/background-mask.avif",
    colorSeats: "/jam/2025/images/remix-color-seats.svg",
    ogThumbnail1: "/jam/2025/images/og-thumbnail-1.jpg",
    ogThumbnail2: "/jam/2025/images/og-thumbnail-2.jpg",
    ogGallery: "/jam/2025/images/og-gallery.jpg",
    tickets: {
      general: "/jam/2025/images/tickets/general.avif",
      ticketHolographic: "/jam/2025/images/tickets/ticket-holographic.avif",
      contributor: "/jam/2025/images/tickets/contributor.avif",
      vip: "/jam/2025/images/tickets/vip.avif",
    },
    keepsakes: {
      photo1: "/jam/2025/images/keepsakes/photo-1.avif",
      photo2: "/jam/2025/images/keepsakes/photo-2.avif",
      poster: "/jam/2025/images/keepsakes/poster.avif",
      pick: "/jam/2025/images/keepsakes/remix-pick.avif",
      ticket: "/jam/2025/images/keepsakes/ticket.avif",
      boardingPass: "/jam/2025/images/keepsakes/boarding-pass.avif",
      sticker: "/jam/2025/images/keepsakes/remix-logo-sticker.svg",
      lanyard: "/jam/2025/images/keepsakes/remix-lanyard.avif",
      torontoPostcard: "/jam/2025/images/keepsakes/toronto-postcard.avif",
    },
  },
  jam2026: {
    horizontalLockup: "/jam/2026/remix-jam-2026-horizontal-lockup.svg",
    shareImage: "/jam/2026/remix-jam-2026-share.jpg",
    floatingTicketCta: "/jam/2026/landing-assets/floating-ticket-cta.svg",
    workshopKeyring: "/jam/2026/landing-assets/remix-keyring-workshop.webp",
    shopifyGlyph: "/jam/2026/landing-assets/shopify-glyph.svg",
    photos: {
      michael: "/jam/2026/photos/remix-jam-2025-michael.avif",
      racingShirt: "/jam/2026/photos/remix-racing-shirt.avif",
      ryan: "/jam/2026/photos/remix-jam-2025-ryan.avif",
      shoppy: "/jam/2026/photos/remix-jam-2025-shoppy.avif",
      torontoCnTower: "/jam/2026/photos/toronto-cn-tower.avif",
    },
    favicons: {
      appleTouchIcon: "/jam/2026/favicons/apple-touch-icon.png",
      favicon16: "/jam/2026/favicons/favicon-16x16.png",
      favicon32: "/jam/2026/favicons/favicon-32x32.png",
      faviconIco: "/jam/2026/favicons/favicon.ico",
    },
  },
} as const;
