export const LOADING_SCREEN_MIN_DISPLAY_MS = 1000;
export const LOADING_SCREEN_FADE_MS = 600;

export const PARTICLE_INTRO_DELAY_MS = 1000;
export const PARTICLE_INTRO_DELAY_S = PARTICLE_INTRO_DELAY_MS / 1000;
