name: deploy

on:
  push:
    branches:
      - staging
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "::set-output name=version::$(cat .nvmrc)"
        id: nvmrc

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"

      - run: echo "::set-output name=dir::$(yarn cache dir)"
        working-directory: ./functions
        id: yarn-cache

      - name: Restore dependency cache
        uses: actions/cache@v2
        with:
          path: "${{ steps.yarn-cache.outputs.dir }}"
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-

      - name: Install dependencies
        run: yarn --frozen-lockfile
        working-directory: ./functions

      - name: Deploy
        working-directory: ./functions
        run: yarn deploy -P ${GITHUB_REF##*/} --token ${{ secrets.FIREBASE_TOKEN }}
